### ISSUE TITLE
feat: new component - Right Hand Side Panel

### ISSUE THREAD

**Issue by yyanwang** [Talend/react-talend-components#126]
@uyildizoglu has provided design of right hand side panel in [guidelines](http://guidelines.talend.com/document/92132#/navigation-layout/side-panel-right)
, and we need it in our project, to embed the form component in it.
I can take this if it's OK.

**Comment by frassinier** [comment]
@jmfrancois has already shown me something like that

**Comment by jsomsanith** [comment]
I think this is a stacked panel un the project isn't it ? @jmfrancois

**Comment by yyanwang** [comment]
Do we already have it? Can't find it in react-talend-components storybook...

**Comment by jsomsanith** [comment]
It's in progress : #59 
You should synchronize with @jmfrancois to see if you can contribute on this component.

**Comment by jmfrancois** [comment]
This is the stacked panel.
We don't know what is the best way to implement it.
It's not finished and not used at the moment.

You can check the PR #59 which is the first implementation draft of this component.
We have multiple issues with it and we are not sure if this way is the one we should follow (using margin).

Two main architecture are possible:

1. using siblings elements in a wrapper
2. using deep elements (< this is the way it's done at the moment)

We really think the fact it's on the right in a kind of drawer is something that should not be done.
The container should be an other components.

Any idea on this ?

I would prefer this to be done using siblings because it's more easy to build Array of props than hierarchical props.

So I would be glade to review and work with you on that point @yyanwang

**Comment by yyanwang** [comment]
Hi, 
You guys seems to put focus on the 'stacking' feature... but what I meant is a single side panel/drawer with certain header and footer(like [design),](http://guidelines.talend.com/document/92132#/navigation-layout/side-panel-right) and I can embed contents in it - more like a container. (oops, seems contradict with the [no children policy](https://github.com/Talend/react-talend-components#no-children-for-leaf).)
In our project, use case of this right hand side panel is to show form on the right side when list item get selected:
https://cdn.frontify.com/api/screen/thumbnail/NUdJDKDtWIFej3uVwTTn1Xwx6ETXwK5_Mo8DhMF50kFyhv2PL7kDzN-2pHwyGbVVYsW9hLQ1h5KJK9Q85Pvw_Q/800
I am thinking:
1, Since this right hand side panel is more like a container, we don't put this in react-talend-components, only implement and use it within our project;
2, Stacked panel is now described in [guidelines](http://guidelines.talend.com/document/92132#/navigation-layout/side-panel-right) as the "Covering type" of right hand side panel. UX design can separate stacked panel from right hand side panel, so we can continue implementation of  stacked panel.
What do you think? @jmfrancois @jsomsanith @frassinier @uyildizoglu

**Comment by uyildizoglu** [comment]
I agree, and no problem to handle them separately. The guideline page is just handling them at once, since they are quite similar. The differences will be emphasized more as an update soon.

**Comment by jsomsanith** [comment]
Hmm really seem to be the same thing.
The stacked panel is a classic drawer that you can stack. So if you only use 1 stack panel, it becomes a simple drawer. I don't think we should create 2 components for that, that would mean to maintain 2 things.

**Comment by yyanwang** [comment]
@jsomsanith For right hand side panel, I need to be able to embed contents in it, can we do it without using {children}? or we can skip this limit for this component?

**Comment by yyanwang** [comment]
Discussed with @jmfrancois , 
Michel will work on stacked panels.
I will work on a drawer in which user can embed any content( very much like RHSP, but without header and footer);

**Comment by jmfrancois** [comment]
fixed by #138
