### ISSUE TITLE
feat: Add id to elements

### ISSUE THREAD

**Issue by yyanwang** [Talend/react-talend-components#64]
I propose to add id to elements for selenium test. 
Take List component as an example, I would like to be able to add a prefix in props, and all children elements of List have an id with [prefix+it's own id].
Does it sound ok to you?

**Comment by jmfrancois** [comment]
Yes we had lots of discussion around this topic.
The main problem of ids is the unicity.
If you build id from the tree it is a non sens because id will change if you change the structure -> the same exact things as class selector.
We don't want to build ids from prefix, it's your choice to inject the id into one component.

So for the list we can imagine at the row level something like this:

```javascript
if (row.id) {
  <RowElement id={`tc-list-row-${row.id}`}>...
}
```
No way to build a system which compute ids.

We may add id on components we know can only be once on our apps

* appheaderbar (you can't have two appheaderbar)
* list
* sidepanel (?)
* layout

You may work on a PR for the list component to support this ?

**Comment by jsomsanith** [comment]
For non dynamic things, perhaps we can just pass the id defined in props.
This is already the case for appheader bar items

```
navItems: [
	{
		type: 'navItem',
		item: { id: 'user-custom-id', icon: 'fa fa-bars', name: 'hello', onClick: action('onClick bars') },
	},
],
```

**Comment by yyanwang** [comment]
ok, so I will just pass id in props. and only for the single occurrence components.
will work on a pull request for this.

**Comment by yyanwang** [comment]
OK, I see what @jsomsanith said, and it can solve part of the problem. now I know how to set id on some specific elements ( for example, navItems).
For some case which elements are also non dynamic, id is missing. For example, the 'Add' button in List toolbar.
Also I agree with @jmfrancois , so I will just add fixed id on single occurrence element, like it did here:
https://github.com/Talend/react-talend-components/blob/master/src/List/Toolbar/SelectSortBy/SelectSortBy.component.js#L43
If this is ok for you, I can work on pull request of this.
Thanks!

**Comment by jsomsanith** [comment]
I disagree with this kind of fix because it prevent you to use the component twice in the same page since the id is fixed.
The last discussion about ids is not finished, but what about passing explicitely ids in defined props. The components could accept optionnal ids to set on defined elements.

**Comment by jmfrancois** [comment]
Oh yes this is bad. We have to change that.

please do it the following: `tc-list-row-${row.id}`
it should let us use the component twice if ids are not the same.
for id we are using uuid so it should not be the case

**Comment by yyanwang** [comment]
I am closing this since #99 has been merged.
